### Get All the Spacefarer
GET http://localhost:4004/GalacticSRV/GalacticSpacefarer HTTP/1.1

### Delete Spacefarer
DELETE http://localhost:4004/GalacticSRV/GalacticSpacefarer/47dbe1c3-95aa-4322-90c5-e2be4d78a0a8 HTTP/1.1


### Create a Spacefarer
POST http://localhost:4004/GalacticSRV/GalacticSpacefarer HTTP/1.1
Content-Type: application/json

    {
      "name": "Black Widow",
      "spacefarerNickName": "BW",
      "email": "BlackWidow@gmail.com",
      "stardustCollection": 101,
      "wormholeNavigationSkill": 5,
      "originPlanet": "Xandar",
      "spacesuitColor": "Black",
      "department_ID": "10b034d9-6b72-4f42-bdbd-956d6d485161",
      "position_ID": "fdc32c72-ef5f-460c-b567-3920bea13e0c"
    }

### Update SpaceFarer StarDust Collection
PATCH http://localhost:4004/GalacticSRV/GalacticSpacefarer/e91ff619-ff06-4912-9a7a-5669924352c8 HTTP/1.1
Content-Type: application/json

    {
      "stardustCollection": 1000
    }

