@AdminCredentials= Basic YWRtaW5Ac2FwLmNvbTppbml0aWFs
@EarthCredentials= Basic ZWFydGhAc2FwLmNvbTppbml0aWFs
@AsgardCredentials= Basic YXNnYXJkQHNhcC5jb206aW5pdGlhbA==
@WakandaCredentials= Basic d2FrYW5kYUBzYXAuY29tOmluaXRpYWw=


### Get All the Spacefarer Using Admin Credentials
GET http://localhost:4004/GalacticSRV/GalacticSpacefarer HTTP/1.1
Authorization: {{AdminCredentials}}

### Get All the Spacefarer Using Earth Credentials
GET http://localhost:4004/GalacticSRV/GalacticSpacefarer HTTP/1.1
Authorization: {{EarthCredentials}}

### Get All the Spacefarer Using Asgard Credentials
GET http://localhost:4004/GalacticSRV/GalacticSpacefarer HTTP/1.1
Authorization: {{AsgardCredentials}}

### Get All the Spacefarer Using Wakanda Credentials
GET http://localhost:4004/GalacticSRV/GalacticSpacefarer HTTP/1.1
Authorization: {{WakandaCredentials}}


### Delete Spacefarer Using Admin Credentials
DELETE http://localhost:4004/GalacticAdminSRV/GalacticSpacefarer/15dd86b9-a1b1-4dfa-b53e-f2c4fd08d438 HTTP/1.1
Authorization: {{AdminCredentials}}

### Create a Spacefarer Using Admin credentials
POST http://localhost:4004/GalacticAdminSRV/GalacticSpacefarer HTTP/1.1
Content-Type: application/json
Authorization: {{AdminCredentials}}

    {
      "name": "Avik Saha",
      "spacefarerNickName": "AS",
      "email": "shaancse08@gmail.com",
      "stardustCollection": 101,
      "wormholeNavigationSkill": 5,
      "originPlanet_ID": "fdc3e7d9-73a0-4f9c-a508-481b6e579fd6",
      "spacesuitColor": "Black",
      "department_ID": "10b034d9-6b72-4f42-bdbd-956d6d485161",
      "position_ID": "fdc32c72-ef5f-460c-b567-3920bea13e0c",
      "imageUrl": "https://media.licdn.com/dms/image/D5603AQF5ds0jd5S71A/profile-displayphoto-shrink_100_100/0/1704192425442?e=1714608000&v=beta&t=bLtiICE2fPmzBrZfEKj20S0H8DvKWKzWfBv6zlGf4bo"
    }

